#!/usr/bin/env node
// Generates docs/ROUTES.md — the inbound-webhook surface and the gate each one
// actually has.
//
// WHY THIS IS GENERATED. A hand-written route table listed all five
// api/members/* endpoints as PUBLIC. They were not; they had been gated on a
// shared secret since they were written. The frontend read the table, probed a
// GET, saw 405 (the method check runs before the auth check, so the request
// never reaches the secret comparison), and correctly stopped to escalate what
// looked like a publicly callable `suspend`.
//
// The labels were wrong because they lived away from the code and nothing could
// tell when they drifted. So this reads the handlers and reports what it finds,
// and tests/webhookSecretGuard.test.ts fails the gate if the committed file
// stops matching.
//
// SCOPE, stated because a document that implies completeness it does not have
// is the same failure in a new place: this covers routes that authenticate
// their CALLER with a shared secret or a signature. It is NOT an inventory of
// all 187 route files, and it says nothing about the session-gated majority.
//
//   node scripts/webhook-routes.mjs           # write docs/ROUTES.md
//   node scripts/webhook-routes.mjs --check    # exit 1 if it would change

import fs from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const OUT = path.join(root, 'docs', 'ROUTES.md')

function walk(dir, out = []) {
  for (const entry of fs.readdirSync(dir).sort()) {
    const full = path.join(dir, entry)
    if (fs.statSync(full).isDirectory()) walk(full, out)
    else if (full.endsWith('.ts')) out.push(full)
  }
  return out
}

const stripComments = (src) => src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/(^|[^:])\/\/[^\n]*/g, '$1')

// The same predicate tests/webhookSecretGuard.test.ts sweeps with. Keyed on the
// env var naming an inbound WEBHOOK, not on the word SECRET — STRIPE_SECRET_KEY
// is an outbound API credential and api/stripe/create-intent.ts is a
// deliberately public checkout endpoint, so asking "does it refuse when its
// secret is missing" of that file is asking the wrong question.
function classify(src) {
  if (src.includes('requireWebhookSecret')) {
    return {
      gate: 'shared secret — `x-webhook-secret` header',
      guard: 'lib/webhookAuth.ts (refuses 500 when WEBHOOK_SECRET is unset)',
    }
  }
  if (src.includes('constructEvent')) {
    return { gate: 'Stripe signature — `stripe-signature` header', guard: 'inline (refuses 500 when the secret is unset)' }
  }
  if (/svix/i.test(src)) {
    return { gate: 'Svix signature — `svix-*` headers', guard: 'inline (refuses 500 when the secret is unset)' }
  }
  if (src.includes('timingSafeEqual')) {
    return { gate: 'HMAC signature — `x-zm-signature` header', guard: 'inline (refuses 500 when the secret is unset)' }
  }
  return null
}

const routes = []
for (const file of walk(path.join(root, 'api'))) {
  const raw = fs.readFileSync(file, 'utf8')
  const src = stripComments(raw)
  const authenticatesCaller = /process\.env\.[A-Z_]*WEBHOOK[A-Z_]*/.test(src) || src.includes('requireWebhookSecret')
  if (!authenticatesCaller) continue

  const rel = path.relative(root, file).replace(/\\/g, '/')
  const info = classify(src)
  if (!info) {
    console.error(`REFUSING TO WRITE: ${rel} authenticates its caller but its gate could not be classified.`)
    console.error('Add the mechanism to classify() rather than letting it fall through to an empty label —')
    console.error('an unlabelled route is how the last table ended up saying PUBLIC.')
    process.exit(1)
  }

  const writes = /\.from\(['"][a-z_]+['"]\)\s*\.(insert|upsert|update|delete)\(/.test(src)
  routes.push({
    route: '/' + rel.replace(/^api\//, 'api/').replace(/\.ts$/, '').replace(/\/index$/, ''),
    file: rel,
    ...info,
    writes,
  })
}

const lines = []
lines.push('# Inbound webhook routes and their gates')
lines.push('')
lines.push('<!-- GENERATED by scripts/webhook-routes.mjs — do not edit by hand.')
lines.push('     tests/webhookSecretGuard.test.ts fails the gate if this drifts. -->')
lines.push('')
lines.push('**None of these is public.** Every route below authenticates its caller before')
lines.push('doing anything, and every one refuses outright when its gating secret is absent')
lines.push('rather than comparing `undefined` to `undefined` and admitting everybody.')
lines.push('')
lines.push('**A `GET` to any of them answers `405`.** The method check runs before the auth')
lines.push('check, so an unauthenticated probe is rejected on the method and never reaches')
lines.push('the secret comparison. That is why these can look unguarded from outside: the')
lines.push('405 says "wrong method", not "you are welcome here". Probe with `POST` and no')
lines.push('header to see the gate — you will get `401`.')
lines.push('')
lines.push('| Route | Gate | Missing-secret behaviour | Writes |')
lines.push('|---|---|---|---|')
for (const r of routes) {
  lines.push(`| \`${r.route}\` | ${r.gate} | ${r.guard} | ${r.writes ? 'yes' : 'no'} |`)
}
lines.push('')
lines.push('## Scope')
lines.push('')
lines.push('This file covers **caller-authenticated webhook routes only** — the surface that')
lines.push('was previously mislabelled. It is not an inventory of every route in `api/`, and')
lines.push('the absence of a route here means only that it does not authenticate via a shared')
lines.push('secret or signature. Session-gated routes use `requireActiveUser` /')
lines.push('`requireAdmin` / `requireCapability`; read the handler.')
lines.push('')
lines.push('`api/stripe/create-intent.ts` is deliberately **not** listed. It reads')
lines.push('`STRIPE_SECRET_KEY`, which is an outbound API credential rather than a gate, and')
lines.push('it is a public checkout endpoint by design.')
lines.push('')

const out = lines.join('\n')
const existing = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null

if (process.argv.includes('--check')) {
  if (existing !== out) {
    console.error('docs/ROUTES.md is out of date. Run: node scripts/webhook-routes.mjs')
    process.exit(1)
  }
  console.log(`docs/ROUTES.md is current (${routes.length} routes).`)
  process.exit(0)
}

fs.mkdirSync(path.dirname(OUT), { recursive: true })
fs.writeFileSync(OUT, out)
console.log(`Wrote docs/ROUTES.md (${routes.length} routes).`)
